CREATE TABLE CIDADE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    UF CHAR(2) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE EMPRESA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(18) UNIQUE,
    ENDERECO VARCHAR(255),
    TELEFONE VARCHAR(20),
    STATUS ENUM('ATIVA', 'INATIVA') DEFAULT 'ATIVA',
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CATEGORIA_PRODUTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) UNIQUE NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE TIPO_PRODUTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) UNIQUE NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




CREATE TABLE PRODUTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ID_TIPO INT,
    ID_CATEGORIA INT,
    MARCA VARCHAR(50),
    CODIGO VARCHAR(50) UNIQUE,
    UNIDADE_MEDIDA VARCHAR(10) DEFAULT 'UN',
    VALOR_UNITARIO DECIMAL(10,2) NOT NULL,
    ESTOQUE_ATUAL INT DEFAULT 0,
    STATUS ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_TIPO) REFERENCES TIPO_PRODUTO(ID),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_PRODUTO(ID)
);




CREATE TABLE CLIENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    DATA_NASCIMENTO DATE,
    CEP VARCHAR(9),
    RUA VARCHAR(100),
    BAIRRO VARCHAR(100),
    ID_CIDADE INT,
    CONTATO VARCHAR(20),
    STATUS ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID)
);


CREATE TABLE FORNECEDOR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    CNPJ VARCHAR(18) UNIQUE NOT NULL,
    CONTATO VARCHAR(20),
    CEP VARCHAR(9),
    RUA VARCHAR(100),
    BAIRRO VARCHAR(100),
    ID_CIDADE INT,
    STATUS ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID)
);

CREATE TABLE USUARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(14) UNIQUE NOT NULL,
    DATA_NASCIMENTO DATE,
    DATA_ADMISSAO DATE,
    PERMISSOES TEXT,
    STATUS ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
    CEP VARCHAR(9),
    RUA VARCHAR(100),
    BAIRRO VARCHAR(100),
    ID_CIDADE INT,
    CONTATO VARCHAR(20),
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID)
);



CREATE TABLE ESTOQUE_EMPRESA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_EMPRESA INT,
    ID_PRODUTO INT,
    ESTOQUE_ATUAL INT DEFAULT 0,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID)
);


CREATE TABLE CONDICAO_PAGAMENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    JUROS DECIMAL(5,2) DEFAULT 0.00,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE FRETE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    STATUS ENUM('ATIVO', 'INATIVO') DEFAULT 'ATIVO',
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE VENDAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA_VENDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_CLIENTE INT,
    ID_USUARIO INT,
    ID_CONDICAO_PAGAMENTO INT,
    ID_FRETE INT,
    FORMA_PAGAMENTO ENUM('À VISTA', 'PARCELADO', 'BONIFICAÇÃO') DEFAULT 'À VISTA',
    NUMERO_PARCELAS INT DEFAULT 1,
    DATA_VENCIMENTO_PARCELA DATE,
    DATA_ENTREGA DATE,
    VALOR_VENDA DECIMAL(10,2) NOT NULL,
    DESCONTO DECIMAL(10,2) DEFAULT 0.00,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    TELEFONE_CONTATO VARCHAR(20),
    RESPONSAVEL_CONTATO VARCHAR(100),
    CEP_ENTREGA CHAR(8),
    RUA_ENTREGA VARCHAR(100),
    BAIRRO_ENTREGA VARCHAR(100),
    ID_CIDADE INT,
    OBSERVACAO TEXT,
    STATUS ENUM('CONCLUÍDA', 'CANCELADA', 'COTAÇÃO', 'PENDENTE') DEFAULT 'PENDENTE',
    ID_EMPRESA INT,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY (ID_CONDICAO_PAGAMENTO) REFERENCES CONDICAO_PAGAMENTO(ID),
    FOREIGN KEY (ID_FRETE) REFERENCES FRETE(ID),
    FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID),
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID)
);



CREATE TABLE ITENS_VENDA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_VENDA INT,
    ID_PRODUTO INT,
    QUANTIDADE INT CHECK (QUANTIDADE BETWEEN 1 AND 1000),
    VALOR_UNITARIO DECIMAL(10,2) NOT NULL,
    ENVIA_LABORATORIO TINYINT(1) DEFAULT 0,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_VENDA) REFERENCES VENDAS(ID),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID)
);



CREATE TABLE COMPRAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA_COMPRA DATE NOT NULL,
    ID_FORNECEDOR INT,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    FORMA_PAGAMENTO ENUM('À VISTA', 'PARCELADO', 'BONIFICAÇÃO'),
    NUMERO_PARCELAS INT DEFAULT 1,
    DATA_VENCIMENTO_PARCELA DATE,
    ID_EMPRESA INT,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID),
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID)
);


CREATE TABLE ITENS_COMPRA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_COMPRA INT,
    ID_PRODUTO INT,
    QUANTIDADE INT CHECK (QUANTIDADE > 0),
    VALOR_UNITARIO DECIMAL(10,2) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRAS(ID),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID)
);

CREATE TABLE CONTAS_A_PAGAR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_COMPRA INT,
    ID_FORNECEDOR INT,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    PARCELA INT,
    VALOR_PARCELA DECIMAL(10,2),
    DATA_PAGAMENTO DATE,
    DATA_VENCIMENTO DATE NOT NULL,
    FORMA_PAGAMENTO ENUM('À VISTA', 'PARCELADO'),
    NUMERO_PARCELAS INT,
    RECORRENTE ENUM('NÃO', 'MENSAL', 'SEMESTRAL', 'ANUAL') DEFAULT 'NÃO',
    DATA_RECORRENCIA DATE,
    STATUS ENUM('PENDENTE', 'PAGO', 'CANCELADO') DEFAULT 'PENDENTE',
    ID_EMPRESA INT,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_COMPRA) REFERENCES COMPRAS(ID),
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDOR(ID),
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID)
);


CREATE TABLE CONTAS_A_RECEBER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_VENDA INT,
    ID_CLIENTE INT,
    VALOR DECIMAL(10,2) NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    DATA_BAIXA DATE,
    VALOR_BAIXA DECIMAL(10,2),
    VALOR_RECEBIDO DECIMAL(10,2),
    STATUS ENUM('PENDENTE', 'RECEBIDO', 'CANCELADO') DEFAULT 'PENDENTE',
    ID_EMPRESA INT,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_VENDA) REFERENCES VENDAS(ID),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID)
);


CREATE TABLE CONCERTO_OCULOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    ID_USUARIO INT,
    ID_EMPRESA INT,
    DATA_ENTRADA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROBLEMA_DESCRITO TEXT,
    SITUACAO ENUM('EM ANÁLISE', 'EM REPARO', 'AGUARDANDO PEÇA', 'PRONTO', 'ENTREGUE') DEFAULT 'EM ANÁLISE',
    OBSERVACAO TEXT,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID)
);


CREATE TABLE LABORATORIO_ENCAMINHAMENTO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_VENDA INT,
    ID_CONCERTO_OCULOS INT,
    DATA_ENCAMINHAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RESPONSAVEL_LABORATORIO VARCHAR(100),
    PREVISAO_ENTREGA DATE,
    STATUS ENUM('ENVIADO', 'EM PRODUÇÃO', 'PRONTO', 'ENTREGUE') DEFAULT 'ENVIADO',
    OBSERVACAO TEXT,
    FOREIGN KEY (ID_VENDA) REFERENCES VENDAS(ID),
    FOREIGN KEY (ID_CONCERTO_OCULOS) REFERENCES CONCERTO_OCULOS(ID)
);


CREATE TABLE LOG_ALTERACOES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TABELA VARCHAR(50) NOT NULL,
    ID_REGISTRO INT NOT NULL,
    ACAO ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
    DADOS_ANTIGOS TEXT,
    DADOS_NOVOS TEXT,
    DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_USUARIO INT,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
);


CREATE TABLE PROMOCAO_ECOMMERCE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ID_PRODUTO INT,
    DESCONTO_PERCENTUAL DECIMAL(5,2) CHECK (DESCONTO_PERCENTUAL BETWEEN 0 AND 100),
    DATA_INICIO DATE,
    DATA_FIM DATE,
    STATUS ENUM('ATIVA', 'INATIVA') DEFAULT 'ATIVA',
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID)
);


CREATE TABLE CARRINHO_COMPRAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ULTIMA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
);


CREATE TABLE ITENS_CARRINHO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CARRINHO INT,
    ID_PRODUTO INT,
    QUANTIDADE INT DEFAULT 1 CHECK (QUANTIDADE > 0),
    DATA_ADICIONADO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CARRINHO) REFERENCES CARRINHO_COMPRAS(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID)
);


CREATE TABLE PEDIDO_ECOMMERCE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    STATUS ENUM('AGUARDANDO PAGAMENTO', 'PAGO', 'ENVIADO', 'ENTREGUE', 'CANCELADO') DEFAULT 'AGUARDANDO PAGAMENTO',
    DATA_PEDIDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ENVIO TIMESTAMP,
    ID_ENDERECO_ENTREGA INT,
    ID_EMPRESA INT,
    TOTAL DECIMAL(10,2),
    FRETE DECIMAL(10,2) DEFAULT 0.00,
    FORMA_PAGAMENTO VARCHAR(20),
    OBSERVACOES TEXT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
    FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID)
);


CREATE TABLE ITENS_PEDIDO_ECOMMERCE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_PEDIDO INT,
    ID_PRODUTO INT,
    QUANTIDADE INT CHECK (QUANTIDADE > 0),
    VALOR_UNITARIO DECIMAL(10,2),
    FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO_ECOMMERCE(ID),
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID)
);


CREATE TABLE MARGEM_LUCRO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CATEGORIA INT,
    MARGEM_PERCENTUAL DECIMAL(5,2) DEFAULT 50,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA_PRODUTO(ID)
);


CREATE TABLE NOTIFICACOES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TIPO VARCHAR(50),
    MENSAGEM TEXT,
    DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LIDA TINYINT(1) DEFAULT 0
);


CREATE TABLE FIDELIDADE_CLIENTE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT UNIQUE,
    PONTOS INT DEFAULT 0,
    ULTIMA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
);




DELIMITER $$

CREATE TRIGGER trg_venda_estoque
AFTER INSERT ON ITENS_VENDA
FOR EACH ROW
BEGIN
    UPDATE PRODUTO 
    SET ESTOQUE_ATUAL = ESTOQUE_ATUAL - NEW.QUANTIDADE,
        DATA_ATUALIZACAO = CURRENT_TIMESTAMP
    WHERE ID = NEW.ID_PRODUTO;

    INSERT INTO LOG_ALTERACOES (TABELA, ID_REGISTRO, ACAO, DADOS_NOVOS, ID_USUARIO)
    SELECT 'PRODUTO', NEW.ID_PRODUTO, 'UPDATE', 'Estoque reduzido', v.ID_USUARIO
    FROM VENDAS v WHERE v.ID = NEW.ID_VENDA;
END$$

DELIMITER ;


DELIMITER $$

CREATE TRIGGER trg_compra_estoque
AFTER INSERT ON ITENS_COMPRA
FOR EACH ROW
BEGIN
    UPDATE PRODUTO 
    SET ESTOQUE_ATUAL = ESTOQUE_ATUAL + NEW.QUANTIDADE,
        DATA_ATUALIZACAO = CURRENT_TIMESTAMP
    WHERE ID = NEW.ID_PRODUTO;

    INSERT INTO LOG_ALTERACOES (TABELA, ID_REGISTRO, ACAO, DADOS_NOVOS, ID_USUARIO)
    VALUES ('PRODUTO', NEW.ID_PRODUTO, 'UPDATE', 'Estoque aumentado', NULL);
END$$

DELIMITER ;


DELIMITER $$

CREATE TRIGGER trg_log_produto
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN
    DECLARE mudancas TEXT DEFAULT '';

    IF OLD.NOME <> NEW.NOME THEN
        SET mudancas = CONCAT(mudancas, 'Nome alterado | ');
    END IF;
    IF OLD.VALOR_UNITARIO <> NEW.VALOR_UNITARIO THEN
        SET mudancas = CONCAT(mudancas, 'Valor alterado | ');
    END IF;
    IF OLD.ESTOQUE_ATUAL <> NEW.ESTOQUE_ATUAL THEN
        SET mudancas = CONCAT(mudancas, 'Estoque alterado | ');
    END IF;
    IF OLD.STATUS <> NEW.STATUS THEN
        SET mudancas = CONCAT(mudancas, 'Status alterado | ');
    END IF;

    IF mudancas <> '' THEN
        INSERT INTO LOG_ALTERACOES (TABELA, ID_REGISTRO, ACAO, DADOS_ANTIGOS, DADOS_NOVOS)
        VALUES ('PRODUTO', NEW.ID, 'UPDATE', 'Alterações detectadas', mudancas);
    END IF;
END$$

DELIMITER ;


DELIMITER $$

CREATE TRIGGER trg_estoque_ecommerce
AFTER INSERT ON ITENS_PEDIDO_ECOMMERCE
FOR EACH ROW
BEGIN
    UPDATE PRODUTO
    SET ESTOQUE_ATUAL = ESTOQUE_ATUAL - NEW.QUANTIDADE,
        DATA_ATUALIZACAO = CURRENT_TIMESTAMP
    WHERE ID = NEW.ID_PRODUTO;
END$$

DELIMITER ;

DELIMITER $$

CREATE TRIGGER trg_limpa_carrinho
AFTER INSERT ON PEDIDO_ECOMMERCE
FOR EACH ROW
BEGIN
    DELETE FROM ITENS_CARRINHO
    WHERE ID_CARRINHO IN (
        SELECT ID FROM CARRINHO_COMPRAS WHERE ID_CLIENTE = NEW.ID_CLIENTE
    );
END$$

DELIMITER ;



DELIMITER $$

CREATE TRIGGER trg_gerar_contas_receber
AFTER INSERT ON VENDAS
FOR EACH ROW
BEGIN
    DECLARE i INT DEFAULT 1;
    DECLARE vencimento DATE;
    DECLARE valor_parcela DECIMAL(10,2);
    
    SET valor_parcela = NEW.VALOR_TOTAL / NEW.NUMERO_PARCELAS;
    SET vencimento = NEW.DATA_VENCIMENTO_PARCELA;

    WHILE i <= NEW.NUMERO_PARCELAS DO
        INSERT INTO CONTAS_A_RECEBER (
            ID_VENDA, ID_CLIENTE, VALOR, DATA_VENCIMENTO, STATUS, ID_EMPRESA
        ) VALUES (
            NEW.ID, NEW.ID_CLIENTE, valor_parcela, DATE_ADD(vencimento, INTERVAL (i - 1) MONTH), 'PENDENTE', NEW.ID_EMPRESA
        );
        SET i = i + 1;
    END WHILE;
END$$

DELIMITER ;


DELIMITER $$

CREATE TRIGGER trg_cria_encaminhamento_lab
AFTER INSERT ON ITENS_VENDA
FOR EACH ROW
BEGIN
    DECLARE status_venda VARCHAR(20);

    IF NEW.ENVIA_LABORATORIO THEN
        SELECT STATUS INTO status_venda FROM VENDAS WHERE ID = NEW.ID_VENDA;

        IF status_venda = 'CONCLUÍDA' THEN
            INSERT INTO LABORATORIO_ENCAMINHAMENTO (
                ID_VENDA, DATA_ENCAMINHAMENTO, STATUS, RESPONSAVEL_LABORATORIO
            ) VALUES (
                NEW.ID_VENDA, CURRENT_TIMESTAMP, 'ENVIADO', 'Sistema'
            );
        END IF;
    END IF;
END$$

DELIMITER ;




DELIMITER $$

CREATE TRIGGER trg_gerar_contas_pagar
AFTER INSERT ON COMPRAS
FOR EACH ROW
BEGIN
    DECLARE i INT DEFAULT 1;
    DECLARE vencimento DATE DEFAULT NEW.DATA_VENCIMENTO_PARCELA;
    DECLARE valor_parcela DECIMAL(10,2);

    IF NEW.NUMERO_PARCELAS > 0 THEN
        SET valor_parcela = NEW.VALOR_TOTAL / NEW.NUMERO_PARCELAS;

        WHILE i <= NEW.NUMERO_PARCELAS DO
            INSERT INTO CONTAS_A_PAGAR (
                ID_COMPRA, ID_FORNECEDOR, VALOR_TOTAL, PARCELA, VALOR_PARCELA,
                DATA_VENCIMENTO, FORMA_PAGAMENTO, NUMERO_PARCELAS, STATUS, ID_EMPRESA
            ) VALUES (
                NEW.ID, NEW.ID_FORNECEDOR, NEW.VALOR_TOTAL, i, valor_parcela,
                DATE_ADD(vencimento, INTERVAL (i - 1) MONTH),
                NEW.FORMA_PAGAMENTO, NEW.NUMERO_PARCELAS, 'PENDENTE', NEW.ID_EMPRESA
            );
            SET i = i + 1;
        END WHILE;
    END IF;
END$$

DELIMITER ;


DELIMITER $$

CREATE TRIGGER trg_reajuste_preco_produto
AFTER INSERT ON ITENS_COMPRA
FOR EACH ROW
BEGIN
    DECLARE margem DECIMAL(5,2) DEFAULT 50;
    DECLARE novo_preco DECIMAL(10,2);

    SELECT COALESCE(m.MARGEM_PERCENTUAL, 50)
    INTO margem
    FROM PRODUTO p
    LEFT JOIN MARGEM_LUCRO m ON m.ID_CATEGORIA = p.ID_CATEGORIA
    WHERE p.ID = NEW.ID_PRODUTO;

    SET novo_preco = NEW.VALOR_UNITARIO * (1 + (margem / 100.0));

    UPDATE PRODUTO
    SET VALOR_UNITARIO = ROUND(novo_preco, 2),
        DATA_ATUALIZACAO = CURRENT_TIMESTAMP
    WHERE ID = NEW.ID_PRODUTO;
END$$

DELIMITER ;


DELIMITER $$

CREATE TRIGGER trg_alerta_estoque_baixo
AFTER UPDATE ON ESTOQUE_EMPRESA
FOR EACH ROW
BEGIN
    IF NEW.ESTOQUE_ATUAL < 5 THEN
        INSERT INTO NOTIFICACOES (TIPO, MENSAGEM)
        VALUES (
            'ESTOQUE BAIXO',
            CONCAT('Produto ', (SELECT NOME FROM PRODUTO WHERE ID = NEW.ID_PRODUTO), ' está com estoque baixo.')
        );
    END IF;
END$$

DELIMITER ;


DELIMITER $$

CREATE TRIGGER trg_pontos_fidelidade
AFTER INSERT ON VENDAS
FOR EACH ROW
BEGIN
    DECLARE pontos INT;

    SET pontos = FLOOR(NEW.VALOR_TOTAL / 10);

    INSERT INTO FIDELIDADE_CLIENTE (ID_CLIENTE, PONTOS, ULTIMA_ATUALIZACAO)
    VALUES (NEW.ID_CLIENTE, pontos, CURRENT_TIMESTAMP)
    ON DUPLICATE KEY UPDATE
        PONTOS = PONTOS + VALUES(PONTOS),
        ULTIMA_ATUALIZACAO = CURRENT_TIMESTAMP;
END$$

DELIMITER ;



CREATE OR REPLACE VIEW vw_estoque_empresa AS
SELECT 
    e.ID AS ID_EMPRESA,
    e.NOME AS EMPRESA,
    p.ID AS ID_PRODUTO,
    p.NOME AS PRODUTO,
    te.ESTOQUE_ATUAL
FROM ESTOQUE_EMPRESA te
JOIN EMPRESA e ON e.ID = te.ID_EMPRESA
JOIN PRODUTO p ON p.ID = te.ID_PRODUTO;


CREATE OR REPLACE VIEW vw_vendas_por_cliente AS
SELECT 
    c.ID AS ID_CLIENTE,
    c.NOME,
    COUNT(v.ID) AS TOTAL_VENDAS,
    SUM(v.VALOR_TOTAL) AS TOTAL_GASTO
FROM VENDAS v
JOIN CLIENTE c ON c.ID = v.ID_CLIENTE
GROUP BY c.ID, c.NOME;



CREATE OR REPLACE VIEW vw_itens_lab_por_venda AS
SELECT 
    v.ID AS ID_VENDA,
    c.NOME AS CLIENTE,
    p.NOME AS PRODUTO,
    iv.QUANTIDADE,
    iv.VALOR_UNITARIO
FROM ITENS_VENDA iv
JOIN VENDAS v ON v.ID = iv.ID_VENDA
JOIN CLIENTE c ON c.ID = v.ID_CLIENTE
JOIN PRODUTO p ON p.ID = iv.ID_PRODUTO
WHERE iv.ENVIA_LABORATORIO = 1;



CREATE OR REPLACE VIEW vw_contas_receber_status AS
SELECT 
    cr.ID_CLIENTE,
    c.NOME,
    cr.STATUS,
    COUNT(*) AS QTDE,
    SUM(cr.VALOR) AS TOTAL
FROM CONTAS_A_RECEBER cr
JOIN CLIENTE c ON c.ID = cr.ID_CLIENTE
GROUP BY cr.ID_CLIENTE, c.NOME, cr.STATUS;


CREATE OR REPLACE VIEW vw_concertos_ativos AS
SELECT 
    co.ID,
    cli.NOME AS CLIENTE,
    co.PROBLEMA_DESCRITO,
    co.SITUACAO,
    co.DATA_ENTRADA,
    co.OBSERVACAO
FROM CONCERTO_OCULOS co
JOIN CLIENTE cli ON cli.ID = co.ID_CLIENTE
WHERE co.SITUACAO IN ('EM ANÁLISE', 'EM REPARO', 'AGUARDANDO PEÇA');


CREATE OR REPLACE VIEW vw_status_pedido_cliente AS
SELECT 
    p.ID,
    c.NOME AS CLIENTE,
    p.STATUS,
    p.DATA_PEDIDO,
    p.DATA_ENVIO,
    p.TOTAL
FROM PEDIDO_ECOMMERCE p
JOIN CLIENTE c ON c.ID = p.ID_CLIENTE;

